name: clone and push project

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          repository: AcekBecek16/template-project-sf
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      - name: Push the Repository
        run: |
          git remote set-url origin https://github.com/AcekBecek16/Repos-API-Testing.git
          git push -u origin main
