name: "Create Project Salesforce"

on: 
  push:
    branches:
      - main

jobs:
  create-project-salesforce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Project Already Exists
        run: |
          if [ -d "sample-project" ]; then
            echo "Project already exists"
            exit 0
          fi
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global
      
      - name: Create Project on Github
        run: sf project generate --name sample-project --template standard
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Create Salesforce project"
          git push
  
