name: "Create Project Salesforce"

on: 
  push:
    branches:
      - main

jobs:
  create-project-salesforce:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global
      
      - name: Create Project on Github
        run: sf project generate --name mywork --template standard
  
